apiVersion: v1
kind: Namespace
metadata:
  name: eidos-namespace
  labels:
    app: eidos
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eidos-deployment
  labels:
    app: eidos
  namespace: eidos-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eidos
  template:
    metadata:
      labels:
        app: eidos
      namespace: eidos-namespace
    spec:
      containers:
        - name: eidos
          image: ghcr.io/khaosresearch/eidos:v1.0.0 # This image must be changed to deploy a custom functions
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: EIDOS_ENV
              valueFrom:
                configMapKeyRef:
                  name: eidos-configmap
                  key: EIDOS_ENV
            - name: EIDOS_ROOT_PATH
              valueFrom:
                configMapKeyRef:
                  name: eidos-configmap
                  key: EIDOS_ROOT_PATH
            - name: EIDOS_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: eidos-configmap
                  key: EIDOS_API_KEY
            - name: EIDOS_FUNCTIONS_FOLDER
              valueFrom:
                configMapKeyRef:
                  name: eidos-configmap
                  key: EIDOS_FUNCTIONS_FOLDER
---
apiVersion: v1
kind: Service
metadata:
  name: eidos-service
  namespace: eidos-namespace
spec:
  type: NodePort
  selector:
    app: eidos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eidos-configmap
  namespace: eidos-namespace
data:
  EIDOS_ENV: "production"
  EIDOS_ROOT_PATH: "/eidos"
  EIDOS_API_KEY: "changeme"
  EIDOS_FUNCTIONS_FOLDER: "functions"
